import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import { Open_Sans } from "next/font/google"; // Note the underscore for Open Sans
import { Manrope } from "next/font/google";
import { cn } from "@/lib/utils";

// Define the Open Sans font with desired weights and subsets
const openSans = Manrope({
  subsets: ["latin"],
  display: "swap", // Optimizes font loading
  // You can specify individual weights or a range, e.g.:
  weight: ["300", "400", "500", "700"],
  // Or, if you want all variable weights (if available for Open Sans):
  // weight: ['variable'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn(openSans.className)}>
        <Toaster />
        {children}
      </body>
    </html>
  );
}
